variable "name"         { type = string }
variable "cpu"          { type = number }
variable "memory"       { type = number }
variable "disk_size"    { type = number }
variable "ip_last_octet"{ type = number }
variable "datastore"    { type = string }
variable "network"      { type = string }
variable "vm_ip_subnet" { type = string }
variable "vm_gateway"   { type = string }
variable "nic_type"     { type = string }
variable "role"         { type = string }
variable "clone_source_vm" { type = string } # existing VM name
