---
# ==============================
# Main VM Configuration Playbook
# ==============================
- name: Configure all VMs (DNS, Users, System, Firewall, Docker DNS)
  hosts: all
  gather_facts: yes
  become: yes
  become_method: sudo
  become_user: root

  vars:
    new_user: template
    timezone: "Africa/Casablanca"

    upstream_dns_servers:
      - 8.8.8.8
      - 1.1.1.1
    fallback_dns_servers:
      - 8.8.4.4
      - 1.0.0.1

  tasks:
    # ✅ Ensure passwordless sudo via /etc/sudoers.d (safe & standard)
    - name: Allow passwordless sudo for Ansible user
      ansible.builtin.copy:
        content: "{{ new_user }} ALL=(ALL) NOPASSWD:ALL\n"
        dest: "/etc/sudoers.d/{{ new_user }}"
        owner: root
        group: root
        mode: '0440'
        validate: 'visudo -cf %s'

    - name: Configure systemd-resolved with DNS
      ansible.builtin.blockinfile:
        path: /etc/systemd/resolved.conf
        block: |
          [Resolve]
          DNS={{ upstream_dns_servers | join(' ') }}
          FallbackDNS={{ fallback_dns_servers | join(' ') }}
          DNSStubListener=yes
        backup: yes
      notify: Restart systemd-resolved

    - name: Ensure /etc/resolv.conf points to systemd-resolved
      ansible.builtin.file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        state: link
        force: yes
      notify: Restart systemd-resolved

    - name: Configure Docker DNS
      ansible.builtin.copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "dns": {{ upstream_dns_servers | to_json }}
          }
        owner: root
        group: root
        mode: '0644'
      notify: Restart Docker

    - name: Ensure hostname resolves in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "127.0.1.1 {{ ansible_hostname }}"
        create: yes
        backup: yes

    - name: Update package cache and upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600

    - name: Set system timezone
      community.general.timezone:
        name: "{{ timezone }}"

    - name: Install essential packages
      ansible.builtin.apt:
        name:
          - vim
          - curl
          - git
          - htop
          - ufw
          - docker.io
        state: present
        install_recommends: no

    - name: Allow SSH through firewall
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: Enable UFW firewall
      community.general.ufw:
        state: enabled
        policy: deny

  handlers:
    - name: Restart systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        state: restarted
        enabled: yes

    - name: Restart Docker
      ansible.builtin.systemd:
        name: docker
        state: restarted
        enabled: yes