---
# ==============================
# Main VM Configuration Playbook
# ==============================
- name: Configure all VMs (DNS, Users, System, Firewall, Docker DNS)
  hosts: all
  become: true
  vars:
    new_user: template
    new_user_password: "{{ 'template' | password_hash('sha512') }}"
    timezone: "Africa/Casablanca"
    upstream_dns_servers:
      - 8.8.8.8
      - 1.1.1.1
    fallback_dns_servers:
      - 8.8.4.4
      - 1.0.0.1
  tasks:
    # ---------- DNS (systemd-resolved) ----------
    - name: Configure systemd-resolved with DNS
      ansible.builtin.blockinfile:
        path: /etc/systemd/resolved.conf
        block: |
          [Resolve]
          DNS={{ upstream_dns_servers | join(' ') }}
          FallbackDNS={{ fallback_dns_servers | join(' ') }}
      notify: Restart systemd-resolved

    - name: Ensure /etc/resolv.conf points to systemd-resolved
      ansible.builtin.file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        state: link
        force: yes
      notify: Restart systemd-resolved

    - name: Flush handlers to apply DNS changes immediately
      ansible.builtin.meta: flush_handlers

    # ---------- Docker DNS fix ----------
    - name: Configure Docker DNS
      ansible.builtin.copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "dns": {{ upstream_dns_servers | to_json }}
          }
      notify: Restart Docker

    # ---------- System setup ----------
    - name: Ensure hostname resolves in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "127.0.1.1 {{ ansible_hostname }}"
        create: yes

    - name: Update package cache and upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Set system timezone
      ansible.builtin.timezone:
        name: "{{ timezone }}"

    - name: Install essential packages
      ansible.builtin.apt:
        name:
          - vim
          - curl
          - git
          - htop
          - ufw
          - docker.io
        state: present

    - name: Create sudo user "{{ new_user }}"
      ansible.builtin.user:
        name: "{{ new_user }}"
        password: "{{ new_user_password }}"
        groups: sudo
        shell: /bin/bash
        create_home: yes

    - name: Allow SSH through firewall
      ansible.builtin.ufw:
        rule: allow
        name: OpenSSH

    - name: Enable UFW firewall
      ansible.builtin.ufw:
        state: enabled
        policy: deny

  handlers:
    - name: Restart systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        state: restarted
        enabled: yes

    - name: Restart Docker
      ansible.builtin.systemd:
        name: docker
        state: restarted
        enabled: yes