---
- name: Main VM Configuration (Security & Basic Setup)
  hosts: all
  become: true
  vars:
    new_user: template
    new_user_password: "{{ 'template' | password_hash('sha512') }}"
    timezone: "Africa/Casablanca"
    dns_servers:
      - 8.8.8.8
      - 1.1.1.1

  tasks:
    ###########################################################################
    # DNS CONFIGURATION (Fix Internet Access)
    ###########################################################################
    - name: Configure DNS
      copy:
        dest: /etc/resolv.conf
        content: |
          {% for ns in dns_servers %}
          nameserver {{ ns }}
          {% endfor %}

    ###########################################################################
    # SYSTEM UPDATES & MAINTENANCE
    ###########################################################################
    - name: Update package cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    ###########################################################################
    # TIMEZONE CONFIGURATION
    ###########################################################################
    - name: Set system timezone
      timezone:
        name: "{{ timezone }}"

    ###########################################################################
    # ESSENTIAL TOOLS INSTALLATION
    ###########################################################################
    - name: Install essential packages
      apt:
        name:
          - vim
          - curl
          - git
          - htop
          - ufw
        state: present

    ###########################################################################
    # USER MANAGEMENT
    ###########################################################################
    - name: Create sudo user "{{ new_user }}"
      user:
        name: "{{ new_user }}"
        password: "{{ new_user_password }}"
        groups: sudo
        shell: /bin/bash
        create_home: yes

    ###########################################################################
    # FIREWALL CONFIGURATION
    ###########################################################################
    - name: Allow SSH through firewall
      ufw:
        rule: allow
        name: OpenSSH

    - name: Enable UFW firewall
      ufw:
        state: enabled
        policy: deny
