---
- name: Configure all VMs (DNS, Users, System, Firewall, Docker DNS)
  hosts: all
  gather_facts: yes
  become: yes
  become_method: sudo
  become_user: root
  serial: "{{ ansible_serial | default(3) }}"
  
  vars:
    new_user: "{{ ansible_ssh_user | default('template') }}"
    timezone: "Africa/Casablanca"
    
    upstream_dns_servers:
      - 8.8.8.8
      - 1.1.1.1
    fallback_dns_servers:
      - 8.8.4.4
      - 1.0.0.1

  pre_tasks:
    - name: Verify connectivity to target hosts
      ansible.builtin.ping:
      tags: always

    # 🔧 CRITICAL: Setup passwordless sudo FIRST
    - name: Setup passwordless sudo for current user
      ansible.builtin.copy:
        content: "{{ new_user }} ALL=(ALL) NOPASSWD:ALL\\n"
        dest: "/etc/sudoers.d/{{ new_user }}"
        owner: root
        group: root
        mode: '0440'
        validate: 'visudo -cf %s'
      tags: ['always', 'sudo']
      # This task will use the password provided via ansible_become_pass

    - name: Verify passwordless sudo works
      ansible.builtin.command: whoami
      become: yes
      changed_when: false
      register: sudo_test
      failed_when: sudo_test.stdout != 'root'
      tags: ['always', 'sudo']

  tasks:
    # Now all subsequent tasks can use passwordless sudo
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: packages

    - name: Install essential packages
      ansible.builtin.apt:
        name:
          - vim
          - curl
          - git
          - htop
          - ufw
          - docker.io
          - docker-compose
          - systemd-resolved
        state: present
        install_recommends: no
      tags: packages

    - name: Set system timezone
      community.general.timezone:
        name: "{{ timezone }}"
      tags: system

    - name: Ensure hostname resolves in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "127.0.1.1 {{ ansible_hostname }}"
        create: yes
        backup: yes
      tags: dns

    - name: Configure systemd-resolved with DNS
      ansible.builtin.blockinfile:
        path: /etc/systemd/resolved.conf
        block: |
          [Resolve]
          DNS={{ upstream_dns_servers | join(' ') }}
          FallbackDNS={{ fallback_dns_servers | join(' ') }}
          DNSStubListener=yes
          Cache=yes
          DNSOverTLS=no
        backup: yes
        marker: "# {mark} ANSIBLE MANAGED DNS BLOCK"
      notify: Restart systemd-resolved
      tags: dns

    - name: Ensure /etc/resolv.conf points to systemd-resolved
      ansible.builtin.file:
        src: /run/systemd/resolve/stub-resolv.conf
        dest: /etc/resolv.conf
        state: link
        force: yes
      notify: Restart systemd-resolved
      tags: dns

    - name: Create Docker daemon configuration directory
      ansible.builtin.file:
        path: /etc/docker
        state: directory
        owner: root
        group: root
        mode: '0755'
      tags: docker

    - name: Configure Docker DNS
      ansible.builtin.copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "dns": {{ upstream_dns_servers | to_json }},
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "10m",
              "max-file": "3"
            }
          }
        owner: root
        group: root
        mode: '0644'
      notify: Restart Docker
      tags: docker

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ new_user }}"
        groups: docker
        append: yes
      tags: docker

    - name: Configure UFW - Allow SSH
      community.general.ufw:
        rule: allow
        name: OpenSSH
      tags: firewall

    - name: Configure UFW - Allow monitoring ports
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - "3000"  # Grafana
        - "9090"  # Prometheus
        - "9093"  # Alertmanager
      tags: firewall

    - name: Enable UFW firewall
      community.general.ufw:
        state: enabled
        policy: deny
        direction: incoming
      tags: firewall

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      tags: packages

  handlers:
    - name: Restart systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        state: restarted
        enabled: yes
        daemon_reload: yes

    - name: Restart Docker
      ansible.builtin.systemd:
        name: docker
        state: restarted
        enabled: yes
        daemon_reload: yes

  post_tasks:
    - name: Verify DNS resolution
      ansible.builtin.command: nslookup google.com
      changed_when: false
      tags: verify

    - name: Verify Docker is running
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
      tags: verify

    - name: Display configuration summary
      ansible.builtin.debug:
        msg:
          - "Configuration completed successfully!"
          - "Hostname: {{ ansible_hostname }}"
          - "IP Address: {{ ansible_default_ipv4.address }}"
          - "DNS Servers: {{ upstream_dns_servers | join(', ') }}"
          - "Docker Status: Running"
          - "Firewall: Enabled"
          - "Passwordless sudo: Configured"
      tags: always