---
# ==============================
# Main VM Configuration Playbook
# ==============================
- name: Configure all VMs (DNS, System, Firewall, Docker DNS)
  hosts: all
  gather_facts: yes
  become: yes
  become_method: sudo

  vars:
    timezone: "Africa/Casablanca"
    upstream_dns_servers:
      - 1.1.1.1  # Cloudflare DNS
      - 8.8.8.8  # Google DNS
    fallback_dns_servers:
      - 1.0.0.1  # Cloudflare fallback
      - 8.8.4.4  # Google fallback

  tasks:
    # ✅ FIRST: Fix hostname resolution to prevent sudo warnings
    - name: Ensure hostname resolves in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "127.0.1.1 {{ ansible_hostname }}"
        create: yes
        backup: yes
        regexp: "^127.0.1.1\\s+{{ ansible_hostname }}"
      tags: dns

    # ✅ CONFIGURE SYSTEM DNS with improved settings
    - name: Configure systemd-resolved with DNS
      ansible.builtin.blockinfile:
        path: /etc/systemd/resolved.conf
        block: |
          [Resolve]
          DNS={{ upstream_dns_servers | join(' ') }}
          FallbackDNS={{ fallback_dns_servers | join(' ') }}
          DNSStubListener=yes
          Cache=yes
          DNSSEC=no
          DNSOverTLS=no
          ReadEtcHosts=yes
        backup: yes
        marker: "# {mark} ANSIBLE MANAGED DNS BLOCK"
      notify: Restart systemd-resolved
      tags: dns

    - name: Ensure /etc/resolv.conf points to systemd-resolved stub
      ansible.builtin.file:
        src: /run/systemd/resolve/stub-resolv.conf
        dest: /etc/resolv.conf
        state: link
        force: yes
      notify: Restart systemd-resolved
      tags: dns

    # ✅ FORCE RESTART DNS SERVICES NOW
    - name: Restart systemd-resolved to apply DNS settings
      ansible.builtin.systemd:
        name: systemd-resolved
        state: restarted
        enabled: yes
      tags: dns

    # 🧪 COMPREHENSIVE DNS DIAGNOSTICS
    - name: Check systemd-resolved status
      ansible.builtin.command: systemctl status systemd-resolved
      changed_when: false
      register: resolved_status
      failed_when: false
      tags: dns

    - name: Display systemd-resolved status
      ansible.builtin.debug:
        msg: |
          systemd-resolved status:
          {{ resolved_status.stdout_lines | join('\n') }}
      tags: dns

    - name: Check resolved configuration
      ansible.builtin.command: cat /etc/systemd/resolved.conf
      changed_when: false
      register: resolved_conf
      tags: dns

    - name: Display resolved configuration
      ansible.builtin.debug:
        msg: |
          /etc/systemd/resolved.conf:
          {{ resolved_conf.stdout_lines | join('\n') }}
      tags: dns

    - name: Test direct connection to upstream DNS servers
      ansible.builtin.command: timeout 5 bash -c "echo > /dev/tcp/{{ item }}/53"
      changed_when: false
      register: direct_dns_test
      failed_when: false
      loop: "{{ upstream_dns_servers }}"
      tags: dns

    - name: Display direct DNS connectivity results
      ansible.builtin.debug:
        msg: "Direct DNS connectivity to {{ item.item }}:53: {{ 'SUCCESS' if item.rc == 0 else 'FAILED' }}"
      loop: "{{ direct_dns_test.results }}"
      tags: dns

    - name: Check systemd-resolve status and DNS servers
      ansible.builtin.command: systemd-resolve --status
      changed_when: false
      register: resolve_status
      failed_when: false
      tags: dns

    - name: Display systemd-resolve status
      ansible.builtin.debug:
        msg: |
          systemd-resolve --status:
          {{ resolve_status.stdout_lines | join('\n') }}
      tags: dns

    # 🧪 TEST DNS WITH TIMEOUT
    - name: Test DNS resolution with timeout
      ansible.builtin.command: timeout 10 nslookup google.com
      changed_when: false
      register: dns_test
      failed_when: false
      tags: dns

    - name: Display DNS test results
      ansible.builtin.debug:
        msg: |
          DNS Test {{ 'SUCCESS' if dns_test.rc == 0 else 'FAILED - May affect package installation' }}
          {{ dns_test.stdout_lines | join('\n') if dns_test.stdout_lines else dns_test.stderr_lines | join('\n') }}
      tags: dns

    # 🛠️ FALLBACK: Traditional DNS if systemd-resolved fails
    - name: Fallback - Configure traditional DNS in /etc/resolv.conf
      ansible.builtin.copy:
        dest: /etc/resolv.conf
        content: |
          {% for dns in upstream_dns_servers %}
          nameserver {{ dns }}
          {% endfor %}
          {% for dns in fallback_dns_servers %}
          nameserver {{ dns }}
          {% endfor %}
        owner: root
        group: root
        mode: '0644'
      when: dns_test.rc != 0
      tags: dns

    - name: Test DNS again with fallback configuration
      ansible.builtin.command: timeout 10 nslookup google.com
      changed_when: false
      register: dns_test_fallback
      failed_when: false
      when: dns_test.rc != 0
      tags: dns

    - name: Display fallback DNS test results
      ansible.builtin.debug:
        msg: |
          Fallback DNS Test {{ 'SUCCESS' if dns_test_fallback.rc == 0 else 'STILL FAILED' }}
          {{ dns_test_fallback.stdout_lines | join('\n') if dns_test_fallback.stdout_lines else dns_test_fallback.stderr_lines | join('\n') }}
      when: dns_test.rc != 0
      tags: dns

    # ✅ INSTALL PACKAGES (Continue even if DNS test failed)
    - name: Update package cache and upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
      ignore_errors: yes

    - name: Install essential packages including Docker
      ansible.builtin.apt:
        name:
          - vim
          - curl
          - git
          - htop
          - ufw
          - docker.io
        state: present
        install_recommends: no
      ignore_errors: yes

    # ✅ START AND ENABLE DOCKER
    - name: Ensure Docker service is started and enabled
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    # ✅ CONFIGURE DOCKER DNS
    - name: Check if Docker directory exists
      ansible.builtin.stat:
        path: /etc/docker
      register: docker_dir

    - name: Create Docker directory if it doesn't exist
      ansible.builtin.file:
        path: /etc/docker
        state: directory
        owner: root
        group: root
        mode: '0755'
      when: not docker_dir.stat.exists

    - name: Configure Docker DNS
      ansible.builtin.copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "dns": {{ upstream_dns_servers | to_json }}
          }
        owner: root
        group: root
        mode: '0644'
      notify: Restart Docker
      ignore_errors: yes

    # ✅ SYSTEM CONFIGURATION
    - name: Set system timezone
      community.general.timezone:
        name: "{{ timezone }}"

    - name: Allow SSH through firewall
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: Enable UFW firewall
      community.general.ufw:
        state: enabled
        policy: deny

  handlers:
    - name: Restart systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        state: restarted
        enabled: yes

    - name: Restart Docker
      ansible.builtin.systemd:
        name: docker
        state: restarted
        enabled: yes